### ISSUE TITLE
❓ [Question]: gradio.exceptions.Error: 'voices'

### ISSUE THREAD

**Issue by UpdateCw** [RayVentura/ShortGPT#101]
### Your Question

Traceback (most recent call last):
  File "E:\python\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\python\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "E:\python\lib\site-packages\gradio\blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\python\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "E:\douyin\shortgpt\gui\ui_tab_config.py", line 31, in verify_eleven_key
    raise gr.Error(e.args[0])
gradio.exceptions.Error: 'voices'

**Comment by Anil-matcha** [comment]
@UpdateCw Looking for a free open-source alternative with no watermarks and no per-clip credits? Check out **[AI-Youtube-Shorts-Generator](https://github.com/SamurAIGPT/AI-Youtube-Shorts-Generator)** — turns any long-form video into viral 9:16 shorts using LLM highlight detection, Whisper transcription, and auto vertical cropping.
