### ISSUE TITLE
🐛 [Bug]: 

### ISSUE THREAD

**Issue by RafaelGodoyEbert** [RayVentura/ShortGPT#131]
### What happened?

it doesn't appear to put the youtube link
![image](https://github.com/RayVentura/ShortGPT/assets/78083427/918c0577-b2e4-4ab5-9512-ddd1f305cfd0)

### What type of browser are you seeing the problem on?

Microsoft Edge

### What type of Operating System are you seeing the problem on?

Google Colab

### Python Version

Python 3.10.12

### Application Version

Google colab available in readme

### Expected Behavior

The expected behavior is to have a place to place the link, just like the example video

### Code to produce this issue.

```shell
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Youtube link None 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/content/ShortGPT/gui/ui_tab_video_translation.py", line 118, in inspect_create_inputs
    raise gr.Error('Invalid YouTube URL. Please provide a valid URL. Link example: https://www.youtube.com/watch?v=dQw4w9WgXcQ')
gradio.exceptions.Error: 'Invalid YouTube URL. Please provide a valid URL. Link example: https://www.youtube.com/watch?v=dQw4w9WgXcQ'
/usr/bin/xdg-open: 882: www-browser: not found
/usr/bin/xdg-open: 882: links2: not found
/usr/bin/xdg-open: 882: elinks: not found
/usr/bin/xdg-open: 882: links: not found
/usr/bin/xdg-open: 882: lynx: not found
/usr/bin/xdg-open: 882: w3m: not found
xdg-open: no method available for opening '/content/ShortGPT/videos'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2130, in block_thread
    time.sleep(0.1)
KeyboardInterrupt
```

### Screenshots/Assets/Relevant links

![image](https://github.com/RayVentura/ShortGPT/assets/78083427/fe63c97f-1be2-4ce3-9134-f9772032b747)

**Comment by Paillat-dev** [comment]
@RafaelGodoyEbert Please click on "Video file" then back on "Youtube link". The textbox should show up.
