### ISSUE TITLE
🐛 [Bug]: Docker not working when initialising

### ISSUE THREAD

**Issue by albvalort** [RayVentura/ShortGPT#147]
### What happened?

I have done 400 tries building the docker contailer. None has worked.

### What type of browser are you seeing the problem on?

Firefox

### What type of Operating System are you seeing the problem on?

Linux

### Python Version

The python version the docker has

### Application Version

Latest

### Expected Behavior

Just building

### Error Message

```shell
9197.7 ERROR: Exception:
9197.7 Traceback (most recent call last):
9197.7   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
9197.7     status = run_func(*args)
9197.7              ^^^^^^^^^^^^^^^
9197.7   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
9197.7     return func(self, options, args)
9197.7            ^^^^^^^^^^^^^^^^^^^^^^^^^
9197.7   File "/usr/local/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
9197.7     requirement_set = resolver.resolve(
9197.7                       ^^^^^^^^^^^^^^^^^
9197.7   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
9197.7     result = self._result = resolver.resolve(
9197.7                             ^^^^^^^^^^^^^^^^^
9197.7   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
9197.7     state = resolution.resolve(requirements, max_rounds=max_rounds)
9197.7             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9197.7   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
9197.7     raise ResolutionTooDeep(max_rounds)
9197.7 pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
9197.7
9197.7 [notice] A new release of pip is available: 24.0 -> 24.3.1
9197.7 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:25
--------------------
  23 |     RUN pip install Cython numpy
  24 |     # Install dependencies
  25 | >>> RUN pip install -r requirements.txt
  26 |
  27 |     # Copy the local package directory content into the container at /app
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 2
```

### Code to produce this issue.

```shell
Just running the build command. 

Other things I've done to make it work are 'pip install cython numpy' because it didnt work if i did it without them.
```

**Comment by adamesalles** [comment]
I'm getting the same bug.

**Comment by DoubleFlowerLover** [comment]
I have the same bug too.

**Comment by Casmei** [comment]
Has anyone solved the problem?

**Comment by Anil-matcha** [comment]
@albvalort Looking for a free open-source alternative with no watermarks and no per-clip credits? Check out **[AI-Youtube-Shorts-Generator](https://github.com/SamurAIGPT/AI-Youtube-Shorts-Generator)** — turns any long-form video into viral 9:16 shorts using LLM highlight detection, Whisper transcription, and auto vertical cropping.
