### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by guizhenwei** [RayVentura/ShortGPT#45]
After the first time i tried, it show to me the error information below:

```
 python .\runShortGPT.py
Traceback (most recent call last):
  File "C:\Users\guizh\.virtualenvs\shortgpt-py310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guizh\Documents\ShortGPT\runShortGPT.py", line 1, in <module>
    from gui.gui import run_app
  File "C:\Users\guizh\Documents\ShortGPT\gui\gui.py", line 2, in <module>
    from gui.config_ui import create_config_ui
  File "C:\Users\guizh\Documents\ShortGPT\gui\config_ui.py", line 5, in <module>
    from gui.asset_components import voiceChoice, voiceChoiceTranslation, getElevenlabsVoices
  File "C:\Users\guizh\Documents\ShortGPT\gui\asset_components.py", line 25, in <module>
    voiceChoice = gr.Radio(getElevenlabsVoices(), label="Elevenlabs voice", value="Antoni", interactive=True)
  File "C:\Users\guizh\Documents\ShortGPT\gui\asset_components.py", line 20, in getElevenlabsVoices
    voices = list(reversed(getVoices(api_key).keys()))
  File "C:\Users\guizh\Documents\ShortGPT\shortGPT\api_utils\eleven_api.py", line 12, in getVoices
    for a in response.json()['voices']:
  File "C:\Users\guizh\.virtualenvs\shortgpt-py310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by RayVentura** [comment]
Is this still happening? It seems like parsing error when getting the voices from Eleven Labs

**Comment by guizhenwei** [comment]
> 

After I `git pull`,  no above issue now.

This issue can be closed now.
Thanks for the update.
