### ISSUE TITLE
Pull the latest code，and run i get this error---->KeyError: 'voices'

### ISSUE THREAD

**Issue by lilinrestart** [RayVentura/ShortGPT#55]
Traceback (most recent call last):
  File "/home/ecs-user/ShortGPT/runShortGPT.py", line 1, in <module>
    from gui.gui import ShortGptUI
  File "/home/ecs-user/ShortGPT/gui/gui.py", line 3, in <module>
    from gui.asset_library_ui import AssetLibrary
  File "/home/ecs-user/ShortGPT/gui/asset_library_ui.py", line 5, in <module>
    from gui.asset_components import (background_music_checkbox,
  File "/home/ecs-user/ShortGPT/gui/asset_components.py", line 44, in <module>
    voiceChoice = gr.Radio(getElevenlabsVoices(), label="Elevenlabs voice", value="Antoni", interactive=True)
  File "/home/ecs-user/ShortGPT/gui/asset_components.py", line 26, in getElevenlabsVoices
    voices = list(reversed(ElevenLabsAPI(api_key).get_voices().keys()))
  File "/home/ecs-user/ShortGPT/shortGPT/api_utils/eleven_api.py", line 17, in get_voices
    self.voices = {voice['name']: voice['voice_id'] for voice in response.json()['voices']}
Traceback (most recent call last):
  File "/home/ecs-user/ShortGPT/runShortGPT.py", line 1, in <module>
    from gui.gui import ShortGptUI
  File "/home/ecs-user/ShortGPT/gui/gui.py", line 3, in <module>
    from gui.asset_library_ui import AssetLibrary
  File "/home/ecs-user/ShortGPT/gui/asset_library_ui.py", line 5, in <module>
    from gui.asset_components import (background_music_checkbox,
  File "/home/ecs-user/ShortGPT/gui/asset_components.py", line 44, in <module>
    voiceChoice = gr.Radio(getElevenlabsVoices(), label="Elevenlabs voice", value="Antoni", interactive=True)
  File "/home/ecs-user/ShortGPT/gui/asset_components.py", line 26, in getElevenlabsVoices
    voices = list(reversed(ElevenLabsAPI(api_key).get_voices().keys()))
  File "/home/ecs-user/ShortGPT/shortGPT/api_utils/eleven_api.py", line 17, in get_voices
    self.voices = {voice['name']: voice['voice_id'] for voice in response.json()['voices']}
KeyError: 'voices'

**Comment by RayVentura** [comment]
Just fixed it, thanks for the issue. https://github.com/RayVentura/ShortGPT/commit/9977914d172cc7ad64762a51656bbb431afecc9c
