### ISSUE TITLE
❓ [Question]: ValueError: An event handler (respond) didn't receive enough output values (needed: 6, received: 3)

### ISSUE THREAD

**Issue by monkeyshichi** [RayVentura/ShortGPT#58]
### Your Question

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 1355, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 1258, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 1233, in validate_outputs
    raise ValueError(
ValueError: An event handler (respond) didn't receive enough output values (needed: 6, received: 3).
Wanted outputs:
    [textbox, chatbot, html, html, button, button]
Received outputs:
    [{'visible': False, '__type__': 'generic_update'}, {'label': None, 'show_label': None, 'container': None, 'scale': None, 'min_width': None, 'visible': None, 'value': [[None, 'Your video is being made now! 🎬']], 'height': None, '__type__': 'update'}, {'label': None, 'show_label': None, 'visible': False, 'value': '', '__type__': 'update'}]

**Comment by ly747688491** [comment]
I also encountered the same problem, whether I run on windows or google colab, I have encountered this problem, I would like to ask if you have solved this problem, or do you know the cause of this problem
我也遇到了这个问题，在windows和 Google Colab上运行都出现了这个问题，我是用python版本3.9和3.10都失败了，请问你解决这个问题了吗，或者你找到问题的原因了吗

**Comment by luohaohaha** [comment]
same issue , any solution?

**Comment by Anil-matcha** [comment]
@monkeyshichi Looking for a free open-source alternative with no watermarks and no per-clip credits? Check out **[AI-Youtube-Shorts-Generator](https://github.com/SamurAIGPT/AI-Youtube-Shorts-Generator)** — turns any long-form video into viral 9:16 shorts using LLM highlight detection, Whisper transcription, and auto vertical cropping.
