### ISSUE TITLE
🐛 [Bug]: Some images does not added to video

### ISSUE THREAD

**Issue by cnwillz** [RayVentura/ShortGPT#78]
### What happened?

I found images added to video are less than the searched result image list.

### What type of browser are you seeing the problem on?

Microsoft Edge

### What type of Operating System are you seeing the problem on?

Windows

### Python Version

3.10

### Application Version

stable branch

### Expected Behavior

images should be added properly

### Error Message

```shell
got the exception stacktrace
`Traceback (most recent call last):
  File "D:\Codebase\ContentGen\shortGPT\editing_framework\core_editing_engine.py", line 59, in generate_video
    clip = self.process_image_asset(asset)
  File "D:\Codebase\ContentGen\shortGPT\editing_framework\core_editing_engine.py", line 212, in process_image_asset
    clip = ImageClip(asset['parameters']['url'])
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\VideoClip.py", line 889, in __init__
    img = imread(img)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\core\imopen.py", line 196, in imopen
    plugin_instance = candidate_plugin(request, **kwargs)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\plugins\pillow.py", line 83, in __init__
    with Image.open(request.get_file()):
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 2994, in open
    im = _open_core(fp, filename, prefix, formats)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 2980, in _open_core
    im = factory(fp, filename)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFile.py", line 112, in __init__
    self._open()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImImagePlugin.py", line 153, in _open
    s = s + self.fp.readline()
AttributeError: 'SeekableFileObject' object has no attribute 'readline'`
```

### Code to produce this issue.

```shell
I add  stacktrace code  to see what exception it throws
shortGPT/editing_framework/core_editing_engine.py 

` elif asset_type == 'image':
                try:
                    print(asset['parameters']['url'])
                    clip = self.process_image_asset(asset)
                    print(clip)
                except Exception as e:
                    traceback.print_exc()
                    continue`
```

### Screenshots/Assets/Relevant links

[Related imageio issue](https://github.com/imageio/imageio/issues/1007)

**Comment by cnwillz** [comment]
Found solution. download image and convert to numpy array, then it works

`
import urllib.request
from PIL import Image
import numpy

def process_image_asset(self, asset: Dict[str, Any]) -> ImageClip:
        temp_file = "temp" + os.path.splitext(asset['parameters']['url'])[-1].lower()
        urllib.request.urlretrieve(asset['parameters']['url'], temp_file)
        img = Image.open(temp_file)
        clip = ImageClip(numpy.array(img))
        return self.process_common_visual_actions(clip, asset['actions'])
`

**Comment by Anil-matcha** [comment]
@cnwillz Looking for a free open-source alternative with no watermarks and no per-clip credits? Check out **[AI-Youtube-Shorts-Generator](https://github.com/SamurAIGPT/AI-Youtube-Shorts-Generator)** — turns any long-form video into viral 9:16 shorts using LLM highlight detection, Whisper transcription, and auto vertical cropping.
