### ISSUE TITLE
🐛 [Bug]: ElevenLabsAPI(api_key).get_voices() requests.exceptions.JSONDecodeError

### ISSUE THREAD

**Issue by guizhenwei** [RayVentura/ShortGPT#84]
### What happened?

Run ```python runShortGPT.py```, it shows requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

### What type of browser are you seeing the problem on?

Microsoft Edge

### What type of Operating System are you seeing the problem on?

Windows

### Python Version

Python 3.10.12

### Application Version

commit 781658c

### Expected Behavior

Be able to launch the default browser to show the UI.

### Error Message

```shell
Traceback (most recent call last):
  File "C:\Users\guizh\.virtualenvs\shortgpt-py310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\guizh\Documents\ShortGPT\runShortGPT.py", line 4, in <module>
    app.launch()
  File "c:\Users\guizh\Documents\ShortGPT\gui\gui_gradio.py", line 32, in launch
    shortGptUI = self.create_interface()
  File "c:\Users\guizh\Documents\ShortGPT\gui\gui_gradio.py", line 25, in create_interface
    self.content_automation = GradioContentAutomationUI(shortGptUI).create_ui()
  File "c:\Users\guizh\Documents\ShortGPT\gui\content_automation_ui.py", line 20, in create_ui
    short_automation_ui = ShortAutomationUI(self.shortGPTUI).create_ui()
  File "c:\Users\guizh\Documents\ShortGPT\gui\ui_tab_short_automation.py", line 36, in create_ui
    AssetComponentsUtils.voiceChoice()
  File "c:\Users\guizh\Documents\ShortGPT\gui\asset_components.py", line 71, in voiceChoice
    cls.getElevenlabsVoices(),
  File "c:\Users\guizh\Documents\ShortGPT\gui\asset_components.py", line 35, in getElevenlabsVoices
    voices = list(reversed(ElevenLabsAPI(api_key).get_voices().keys()))
  File "c:\Users\guizh\Documents\ShortGPT\shortGPT\api_utils\eleven_api.py", line 11, in __init__
    self.get_voices()
  File "c:\Users\guizh\Documents\ShortGPT\shortGPT\api_utils\eleven_api.py", line 20, in get_voices
    self.voices = {voice['name']: voice['voice_id'] for voice in response.json()['voices']}
  File "C:\Users\guizh\.virtualenvs\shortgpt-py310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```
```


### Code to produce this issue.

```shell
python .\runShortGPT.py
```

**Comment by RayVentura** [comment]
The elevenlabs voice list request to their API probably failed. Usually, it sometimes gives the ``Unusual activity detected`` error if you're on VPN, which might have caused the crash.

**Comment by Anil-matcha** [comment]
@guizhenwei Looking for a free open-source alternative with no watermarks and no per-clip credits? Check out **[AI-Youtube-Shorts-Generator](https://github.com/SamurAIGPT/AI-Youtube-Shorts-Generator)** — turns any long-form video into viral 9:16 shorts using LLM highlight detection, Whisper transcription, and auto vertical cropping.
